spring.application.name=ProductsMicroservice

# port 0 ?? ???? ??? Random port number? ???
server.port=0


# kafka Producer??? --bootstrap-server??
spring.kafka.producer.bootstrap-servers=localhost:9092,localhost:9094
# ??? key default serializer??
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
# ??? value default serializer??
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer

